################ Chinese language ##################
[zh]
languageName = "Zh"
languageCode = "zh-cn"
contentDir = "content/chinese"
weight = 2

################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
