################ Chinese language ##################
[zh]
languageName = "Cn"
languageCode = "zh-cn"
contentDir = "content/chinese"
weight = 1

################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 0
