############# English navigation ##############

# main menu
[[main]]
name = "主页"
url = "/"
weight = 1

[[main]]
name = "导师"
url = "about/"
weight = 2

[[main]]
name = "成员"
url = "authors/"
weight=3

[[main]]
name = "项目"
url = "blog/"
weight = 4

[[main]]
name = "论文"
url = "elements/"
weight = 5

[[main]]
name = "联系"
url = "contactus/"
weight = 6

[[main]]
name = "更多"
hasChildren = true
weight = 7

[[main]]
parent = "更多"
name = "分类"
url = "categories/"

[[main]]
parent = "更多"
name = "最新动态"
url = "news/"



# footer menu
[[footer]]
name = "关于"
url = "about/"
weight = 1

[[footer]]
name = "论文"
url = "elements/"
weight = 2

[[footer]]
name = "隐私条款"
url = "privacy-policy/"
weight = 3